# Generated by Django 4.2.4 on 2023-10-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_store_jar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
