# Generated by Django 4.2.4 on 2023-10-12 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_alter_dashboardstatus_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardstatus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
