# Generated by Django 4.2.4 on 2023-10-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_dashboardstatus_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='jars_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
