# Generated by Django 4.2.4 on 2023-12-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_trip_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardStatus',
        ),
    ]
