# Generated by Django 4.2.4 on 2024-01-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_trip_jars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='jars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
